server {
    listen 80;
    server_name _;

    location / {
        return 301 /momo-store/;
    }

    location /momo-store/ {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /momo-store/index.html;
    }
}
